### ISSUE TITLE
Obtain emissions intensity factors for generators with missing data

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#107]
We have 7 facilities with an unknown emissions intensity factor:

```
BIOGAS01 (Richgro) in WEM WEM with fueltech bioenergy_biogas is missing factor
HENDERSON_RENEWABLE_IG1 (Henderson) in WEM WEM with fueltech bioenergy_biogas is missing factor
BRIDGETOWN_BIOMASS_PLANT (Manjimup) in WEM WEM with fueltech bioenergy_biomass is missing factor
GOSNELLS (Gosnells) in WEM WEM with fueltech bioenergy_biogas is missing factor
ATLAS (Mirrabooka) in WEM WEM with fueltech bioenergy_biogas is missing factor
SNAPPER1 (Snapper Point) in NEM SA1 with fueltech gas_ocgt is missing factor
HEZ1 (Hunter Economic Zone) in NEM NSW1 with fueltech distillate is missing factor
```

For each we need a factor (tCO₂/MWh) and a source for the data.

**Comment by simonhac** [comment]
@aleith are you able to help with any of these?

**Comment by simonhac** [comment]
With regards to Snapper Point, it's a bunch of GE TM2500 generators that came from the SA Temporary Generators. When I wrote a [fact check on the SA Temporary Generators](https://reneweconomy.com.au/frydenberg-factcheck-s-really-burning-80000l-diesel-hour-keep-lights-84966/), I found that they were rated at 0.750 tCO₂/MWh, but I have lost the source.

**Comment by nc9** [comment]
These can be updated + pull-requested here:

https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L26786

without code intervention - github actions will update dev

**Comment by aleith** [comment]
i'm combining the CER data and scada/openem data for WEM/SWIS into a single spreadsheet for comparison of data. i'll take a look at these in due course. i just got the scada hourly data totalled into annual export per facility/unit for FY21, so will be a three way comparison. there's some big differences already.

**Comment by simonhac** [comment]
@aleith, btw, so far all of the emissions factors we're using come from official publications. so ideally we'd like a document name and URL.

**Comment by aleith** [comment]
These are the landfill gas power facilities listed for WA on the SWIS in the CEG reporting FY21:


CK WILLIAM AUSTRALIA HOLDINGS PTY LTD | Red Hill LFG Power Station | WA | 21,499 | 1,656 | 0.08 | On | SWIS | Landfill Gas
-- | -- | -- | -- | -- | -- | -- | -- | --
CK WILLIAM AUSTRALIA HOLDINGS PTY LTD | Tamala Park LFG Power Station | WA | 32,599 | 2,508 | 0.08 | On | SWIS | Landfill Gas
LMS ENERGY PTY LTD | South Cardup Renewable Energy Facility | WA | 18,626 | 1,476 | 0.08 | On | SWIS | Landfill Gas
SUSTAINABLE ENERGY INFRASTRUCTURE HOLDINGS PTY LIMITED | Rockingham Landfill | WA | 11,434 | 1,384 | 0.12 | On | SWIS | Landfill Gas

There are no facilities in the CER SGM reporting that have biogas as a fuel type. the closest is bagasse (sugar cane waste). I guess they're all below the reporting threshold of the SG mechanism.

**Comment by aleith** [comment]
Interestingly I just read in the CER spreadsheet that AEMO reporting is different and includes Scope three fugitive methane emissions… do tell! Also need to consider parasitic load (running the generation facility itself) in all this.

> The emissions intensities reported here are defined as National Greenhouse and Energy Reporting (NGER) Scope 1 emissions (t CO2-e) divided by NGER electricity production. Electricity production is based on total generation reported through NGER, including the use of electricity by the power station itself. The emissions intensities in this report are based on data as reported to the Clean Energy Regulator, and no adjustment has been made to reflect any specific circumstances. Emissions intensities elsewhere are more typically measured (including by the Australian Energy Market Operator (AEMO)) based on energy sent out to the grid, which results in a higher emissions intensity per power station. Other differences from AEMO estimates include that AEMO specify the emissions intensity of renewables generators at zero (whereas many renewables generators have some actual emissions from backup generation) and also include scope 3 emissions from fugitive sources. AEMO also undertake revisions for a small number of power stations to reflect some station specific factors.

**Comment by simonhac** [comment]
@aleith can you please add column headings to the table above? and are any of these stations the same as the ones in the first post of this issue?

(for the purposes of OpenNEM we are interested in average emissions factor, not an emissions-load curve.)

**Comment by nc9** [comment]
I've put in our estimates for now - I'm going to leave this issue open for now until we get verified values for the estimates but I'll lower the priority

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/39009487/212789032-74c81519-b34d-4f3d-bdec-f95f9a931b9e.png">

**Comment by nc9** [comment]
|code                    |network_id|network_region|fueltech_id      |emissions_factor_co2|emission_factor_source|
|------------------------|----------|--------------|-----------------|--------------------|----------------------|
|AGLNOW1                 |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|AGLSITA1                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|AWABAREF                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|BWTR1                   |NEM       |NSW1          |bioenergy_biogas |0.018               |                      |
|CONDONG1                |NEM       |NSW1          |bioenergy_biogas |0.018               |                      |
|EASTCRK                 |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|EASTCRK2                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|GRANGEAV                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|JACKSGUL                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|KINCUM1                 |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|LUCAS2S2                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|LUCASHGT                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|WDLNGN01                |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|WOYWOY1                 |NEM       |NSW1          |bioenergy_biogas |0.062               |                      |
|BPLANDF1                |NEM       |QLD1          |bioenergy_biogas |0.062               |                      |
|EDLRGNRD                |NEM       |QLD1          |bioenergy_biogas |0.062               |                      |
|ICSM                    |NEM       |QLD1          |bioenergy_biomass|0.018               |                      |
|INVICTA                 |NEM       |QLD1          |bioenergy_biomass|0.018               |                      |
|PIONEER                 |NEM       |QLD1          |bioenergy_biomass|0.018               |                      |
|RACOMIL1                |NEM       |QLD1          |bioenergy_biomass|0.018               |                      |
|ROCHEDAL                |NEM       |QLD1          |bioenergy_biogas |0.062               |                      |
|RPCG                    |NEM       |QLD1          |bioenergy_biomass|0.023               |                      |
|STAPYLTON1              |NEM       |QLD1          |bioenergy_biogas |0.062               |                      |
|SUNCOAST                |NEM       |QLD1          |bioenergy_biomass|0.0216              |                      |
|TABMILL2                |NEM       |QLD1          |bioenergy_biomass|0.018               |                      |
|TITREE                  |NEM       |QLD1          |bioenergy_biogas |0.062               |                      |
|VICMILL1                |NEM       |QLD1          |bioenergy_biomass|0.018               |                      |
|WHIT1                   |NEM       |QLD1          |bioenergy_biogas |0.062               |                      |
|BOLIVAR1                |NEM       |SA1           |bioenergy_biogas |0.003               |                      |
|HIGHBRY1                |NEM       |SA1           |bioenergy_biogas |0.0576              |                      |
|PEDLER1                 |NEM       |SA1           |bioenergy_biogas |0.06                |                      |
|TEATREE1                |NEM       |SA1           |bioenergy_biogas |0.0576              |                      |
|WINGF1_1                |NEM       |SA1           |bioenergy_biogas |0.062               |                      |
|WINGF2_1                |NEM       |SA1           |bioenergy_biogas |0.062               |                      |
|REMOUNT                 |NEM       |TAS1          |bioenergy_biogas |0.062               |                      |
|BERWICK                 |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|BROADMDW                |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|BROOKLYN                |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|CLAYTON                 |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|CORIO1                  |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|HALAMRD1                |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|MORNW                   |NEM       |VIC1          |bioenergy_biogas |0.06                |                      |
|SHEP1                   |NEM       |VIC1          |bioenergy_biogas |0.023               |                      |
|SVALE1                  |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|TATURA01                |NEM       |VIC1          |bioenergy_biogas |0.023               |                      |
|WOLLERT1                |NEM       |VIC1          |bioenergy_biogas |0.062               |                      |
|WYNDW                   |NEM       |VIC1          |bioenergy_biogas |0.06                |                      |
|ATLAS                   |WEM       |WEM           |bioenergy_biogas |0.057               |opennem_estimated     |
|BIOGAS01                |WEM       |WEM           |bioenergy_biogas |0.057               |opennem_estimated     |
|BRIDGETOWN_BIOMASS_PLANT|WEM       |WEM           |bioenergy_biomass|0.057               |opennem_estimated     |
|GOSNELLS                |WEM       |WEM           |bioenergy_biogas |0.057               |opennem_estimated     |
|HENDERSON_RENEWABLE_IG1 |WEM       |WEM           |bioenergy_biogas |0.057               |opennem_estimated     |
|KALAMUNDA_SG            |WEM       |WEM           |bioenergy_biogas |0.057               |opennem_estimated     |
|RED_HILL                |WEM       |WEM           |bioenergy_biogas |0.05                |                      |
|ROCKINGHAM              |WEM       |WEM           |bioenergy_biogas |0.07                |                      |
|SOUTH_CARDUP            |WEM       |WEM           |bioenergy_biogas |0.06                |                      |
|TAMALA_PARK             |WEM       |WEM           |bioenergy_biogas |0.05                |                      |

**Comment by nc9** [comment]
@simonhac 

https://gist.github.com/nc9/1e6615b9a390c8743a4f1f9102dd4f29

**Comment by nc9** [comment]
scanning the output both `TATURA01` and `BOLIVAR1` look wrong in that

**Comment by simonhac** [comment]
@nc9 please:
* leave `TATURA01` and `BOLIVAR` as they are
* change `SNAPPER01` to 0.750 tCO₂/MWh
* change `HEZ1` to the average of all diesel units… should be something between 0.7 and 1.1 (i think).

**Comment by nc9** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/39009487/213057785-122a486f-5dc2-4ec0-89b4-6f829ae4414a.png">

updated now to that value for `HEZ1`

**Comment by simonhac** [comment]
thanks… not ideal, but i bet it barely runs.

weird that there's no generation before april 2022… it was commissioned a decade ago:
![image](https://user-images.githubusercontent.com/20500649/213059662-f2438e54-8c21-4ee3-900c-d842f6b77c91.png)

note that it is _not_ the controversial [hunter power project](https://www.snowyhydro.com.au/hunter-power-project/), **_as marked_**, which hasn't been built yet, but actually the [HEZ power station](https://www.yumpu.com/en/document/view/2654264/hez-power-station-nsw).

**Comment by aleith** [comment]
> @aleith can you please add column headings to the table above? and are any of these stations the same as the ones in the first post of this issue?
> 
> (for the purposes of OpenNEM we are interested in average emissions factor, not an emissions-load curve.)

only just saw this today @simonhac 

here's the headings and maybe other columns direct from the CER SG mechanism reporting Excel file (I believe so, I extended it in other columns not shown here it for my own purposes including to compare OpenNEM and AEMO data)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/aleith/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/aleith/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Reporting   entity | Facility name | Type | State | Electricity production   (GJ) | Electricity production   (MWh) | Total scope 1 emissions        (t CO2-e) | Total scope 2 emissions        (t CO2-e) | Total emissions      (t CO2-e) | Emission intensity      (t CO2-e/ MWh) | Grid connected | Grid | Primary fuel
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CK WILLIAM AUSTRALIA HOLDINGS   PTY LTD | Red Hill LFG Power Station | F | WA | 77,397 | 21,499 | 1,654 | 2 | 1,656 | 0.08 | On | SWIS | Landfill Gas
CK WILLIAM AUSTRALIA HOLDINGS   PTY LTD | Tamala Park LFG Power Station | F | WA | 117,355 | 32,599 | 2,505 | 3 | 2,508 | 0.08 | On | SWIS | Landfill Gas
LMS ENERGY PTY LTD | South Cardup Renewable Energy   Facility | F | WA | 67,055 | 18,626 | 1,476 | 0 | 1,476 | 0.08 | On | SWIS | Landfill Gas
SUSTAINABLE ENERGY   INFRASTRUCTURE HOLDINGS PTY LIMITED | Rockingham Landfill | F | WA | 41,162 | 11,434 | 1,384 | 0 | 1,384 | 0.12 | On | SWIS | Landfill Gas



</body>

</html>
