### ISSUE TITLE
Incorrect calculation for VWP

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#109]
![image](https://user-images.githubusercontent.com/39009487/183237923-babff067-d24d-4f2d-b386-8c1a29c67853.png)

comparing 

https://opennem.org.au/energy/vic1/?range=30d&interval=1d

to @dylanjmcconnell VWP output discrepancy

**Comment by simonhac** [comment]
@nc9 is adding two new series to the daily and monthly summary JSONs:
* `*.demand.energy` — sum of `demand_and_nonschedgen` for each interval
*  `*.demand.market_value` — sum of `demand_and_nonschedgen * price` for each interval

**Comment by nc9** [comment]
https://data.dev.opennem.org.au/v3/stats/au/NEM/VIC1/energy/2022.json

**Comment by nc9** [comment]
This file :

https://github.com/opennem/opennem/blob/master/scripts/vwp.py

Tests the VWP deltas - they're all down to rounding errors. @dylanjmcconnell can you re-run what you had before in the original just to confirm please?

**Comment by simonhac** [comment]
@nc9 why does VWP only start in 2009? ie. what data is missing to take it back to start of the NEM?

![Image](https://user-images.githubusercontent.com/20500649/230004244-aa2ccd11-3458-47d7-9e53-4c6aed61287c.png)

**Comment by nc9** [comment]
oh! need to re-run the aggregate that takes the new demand data for years < 2009

I'll do that now

**Comment by nc9** [comment]
re-assigned this issue to track

**Comment by nc9** [comment]
![image](https://github.com/opennem/opennem/assets/39009487/0273cee4-0353-4342-936b-b4b005771158)

price < 2009 on prod. (q came up if we should have an inflation-adjusted option @simonhac which we do in stripes )

**Comment by nc9** [comment]
#283 - validate and document OpenNEM VWP
