### ISSUE TITLE
Ensure Statuspage notices stalled network syncs

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#111]
On Saturday 6 August, OpenNEM didn't process NEM data for almost 5 hours:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/20500649/183239828-588fc527-8772-4eba-ac6f-28305f4ee95e.png">

…yet [our Statuspage](https://status.opennem.org.au/) said everything was hunky-dory:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/20500649/183239779-1490308f-b893-4a5b-94ea-a0963c6f7b90.png">

We need to show unexpected delays as downtime.

**Comment by nc9** [comment]
merged into #334
