### ISSUE TITLE
Speed up station data API

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#113]
Station API request is taking about 6.5s on _first fetch_. As a user this feels really sluggish. The database should be 'expecting' these kind of requests and should return in less than 1 second, preferably less than 100ms.

https://api.opennem.org.au/stats/energy/station/NEM/LOYYANGA?period=all&interval=1M

<img width="988" alt="image" src="https://user-images.githubusercontent.com/20500649/183241193-95b8f0d2-41c4-49a4-9e7e-d11523fdc199.png">

**Comment by nc9** [comment]
This is definitely a regression. Will look into optimizing that query.

**Comment by simonhac** [comment]
please add a response time panel to our statuspage for this… but how do you ensure that we don't get an artificially low response time because we're continually warming up the cache?

<img width="417" alt="image" src="https://user-images.githubusercontent.com/20500649/183273719-2a6a3a30-5603-4ef3-bc94-439c698b2bd8.png">

**Comment by aleith** [comment]
I was noticing this when viewing the (mostly SWIS) facilities pages. generates the default 7 day graph quite fast but as soon as you click the "ALL" tab it can take many seconds to return the initial graph. just checked and was fine, but its more often than not sluggish to grab the historical data, once it has it graph redraws using different intervals are fast (all happens front end I guess).

**Comment by nc9** [comment]
![image](https://user-images.githubusercontent.com/39009487/188032705-c1864f8f-a650-4a6e-bdb9-d729fa1b17e6.png)

![image](https://user-images.githubusercontent.com/39009487/188032730-001e8ebf-e385-41cf-9a59-77e4ac6c913a.png)

much better - more to do here on the db end with indexes but I'll file that separately
