### ISSUE TITLE
Bad historical solar data 

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#119]
Solar data has some weird 'oscillations' from June – September 2005, then builds gradually to February 2010, then sits at ~0 until 2018. Also has 9 days of zeros at the end, which is today (not yet computed) plus 8 days into the future.
 
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/20500649/183559065-04423835-2321-460f-bdc5-309dbdb7d591.png">

**Comment by nc9** [comment]
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/39009487/212823222-5a22f5f9-9282-4775-ad4e-1030d720eec9.png">
