### ISSUE TITLE
WCMGas summary series missing data in daily aggregates

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#122]
summary series for waste coal mine gas (WCMG) shows no data before june 2021:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/20500649/183836876-b8ebb572-09c6-44ed-a835-18808062f7c4.png">

but there was WCMG generation prior to this date. 

eg:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/20500649/183836748-dee5e8bb-0c51-44ad-a813-7a11305ec41f.png">

and:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/20500649/183837107-d0ce79e1-5cf4-4558-bead-4c8a583a2fa3.png">

**Comment by nc9** [comment]
see #190 merged into there

**Comment by nc9** [comment]
![image](https://user-images.githubusercontent.com/39009487/228183865-40f067f2-c8fc-41bb-a608-bf842787d3f0.png)

on dev @simonhac

**Comment by simonhac** [comment]
seeing a very strange emissions intensity: 
<img width="971" alt="image" src="https://user-images.githubusercontent.com/20500649/228687452-8b178690-79d5-4a6d-a13c-9e57e3fc3939.png">

**Comment by nc9** [comment]
check the json debug output for emission intensity

**Comment by gmmspi** [comment]
@nc9 not ready to close, weird emissions intensity persists on dev and prod:
https://dev.opennem.org.au/energy/nem/?range=all&interval=1M

When you select NEM it shows the strange emissions intensity, when you selected Queensland it looks normal

**Comment by simonhac** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/20500649/230758488-310c2c8e-6b28-4875-9a0a-cd5deaf05e2f.png">

**Comment by nc9** [comment]
the `QLD` and `NEM` outputs should be identical - since the facilities are only in qld. at the moment its showing the same energy values and same emission outputs but different intensities:

NEM:

![image](https://user-images.githubusercontent.com/39009487/231015308-e09e8042-2cbf-42c3-b02d-3ec04639d4c8.png)

QLD:

![image](https://user-images.githubusercontent.com/39009487/231015353-10336852-19bf-4ad9-8f6c-a38c9ef3e949.png)


closer to narrowing down what that is

**Comment by nc9** [comment]
console shows that intensity output 

![image](https://user-images.githubusercontent.com/39009487/231018036-eef96a59-5f62-4965-bf7c-670409b99e17.png)

the one below doesn't look right either - i'll find where that is being output

**Comment by gmmspi** [comment]
Resolved by no longer subtracting battery discharge from totalPowerEnergy used in the emissions intensity equation. Deployed to: https://7f8ef5f4.opennem-fe-bl7.pages.dev/

**Comment by nc9** [comment]
I really like the branch builds - I'll do the same on the BE using railway. and we'll figure out a way to point them to one another

**Comment by gmmspi** [comment]
Resolved and deployed to prod
