### ISSUE TITLE
price and demand IDs are inconsistent

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#127]
from [7d.json](https://data.opennem.org.au/v3/stats/au/NEM/power/7d.json):

![image](https://user-images.githubusercontent.com/20500649/186324670-e683f86c-248e-4417-8f55-b0bea2d9687b.png)

**Comment by simonhac** [comment]
and from [2022.json](https://data.opennem.org.au/v3/stats/au/NEM/energy/2022.json):
![image](https://user-images.githubusercontent.com/20500649/186325105-174504e6-3b65-4ee4-9a06-0d41982083dd.png)

**Comment by simonhac** [comment]
and from [monthly.json](https://data.opennem.org.au/v3/stats/au/all/monthly.json):
![image](https://user-images.githubusercontent.com/20500649/186325417-1f380cbc-aa17-4e6e-83ed-c31816f1f09f.png)

and from [daily.json](https://data.opennem.org.au/v3/stats/au/NSW1/daily.json)
![image](https://user-images.githubusercontent.com/20500649/186325682-84636d9f-cfef-43b5-87bd-30ab9bb78328.png)

**Comment by simonhac** [comment]
Obviously, any tweaks here will affect clients, eg. our front end and any external users.

**Comment by nc9** [comment]
![image](https://user-images.githubusercontent.com/39009487/188031526-b7677d93-9c6c-4656-a0ff-8d7327d6cb41.png)
