### ISSUE TITLE
Demand ids in year jsons do not match

### ISSUE THREAD

**Issue by chienleng** [opennem/opennem#133]
compare:
* 2021: https://data.opennem.org.au/v3/stats/au/NEM/energy/2021.json
* 2022: https://data.opennem.org.au/v3/stats/au/NEM/energy/2022.json

2021 has `nem.nem.demand.energy` and `nem.nem.demand.market_value`
2022 has `au.nem.demand.energy` and `au.nem.demand.market_value`

FE issue: https://github.com/opennem/opennem-fe/issues/115
These ids are used to match and merge the data series for multi year jsons in the FE.

**Comment by nc9** [comment]
Check the version header it’s mid-writing atm

**Comment by nc9** [comment]
They're writing out again at the moment - I'll ping you once they're done

**Comment by nc9** [comment]
these are done 👍

**Comment by simonhac** [comment]
[NSW1/energy/2022.json](https://data.opennem.org.au/v3/stats/au/NEM/NSW1/energy/2022.json) is still broken, at least when generated `2022-09-05T08:39:48+10:00`:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/20500649/188350834-b75b5956-3a9a-4114-8665-df63b69edf44.png">

**Comment by nc9** [comment]
ACK - on it in a moment
