### ISSUE TITLE
json file length checking not working

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#134]
when energy and power logs are written out we are supposed to check the length.

in [this weekly data](https://data.opennem.org.au/v3/stats/historic/weekly/NEM/NSW1/year/2022/week/32.json) file ([32.json.zip](https://github.com/opennem/opennem/files/9486414/32.json.zip)), the `au.nem.demand.market_value` entry is supposed to contain 5m intervals from `2022-08-08T10:00:00+10:00` to `2022-08-15T10:00:00+10:00` inclusive, which should be 2017 entries.

instead it only has 8 entries:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/20500649/188352650-9a2e3cad-ff78-4aa7-87c0-d94259b3ca1e.png">

not only is there a problem with the data, but we're supposed to be validating these files on output. this one slipped through.

**Comment by nc9** [comment]
fixed in f32d859af4150e28d33f23068d6929f0931ecd7a
