### ISSUE TITLE
rooftop solar prior to march 2018 has gone missing

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#138]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/20500649/191896988-e27d9c30-093c-472f-a475-6493607d87ac.png">

* NSW goes back to ~october 2015 because there was _utility_ solar in the state.

**Comment by aleith** [comment]
there have been issues with WA Rooftop Solar on the main Energy graphs but only when the duration = "ALL".

in the past the historical years where there but no data from 1 dec 2022 onwards (IIRC)

Today it's all gone. 

I'll log it as seperate bug but it may be related.
