### ISSUE TITLE
Tasmania import emissions incorrect

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#144]
![image](https://user-images.githubusercontent.com/39009487/198285644-84cc94aa-4d2c-4a49-894d-fbee3fccbbf7.png)

Potentially reversed intensities

**Comment by nc9** [comment]
This was specific to TAS and imports only @simonhac 

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/39009487/199888378-fdad960b-011c-48b4-977f-413c65703c3e.png">

**Comment by nc9** [comment]
related to #160

**Comment by nc9** [comment]
https://dev.opennem.org.au/energy/tas1/?range=30d&interval=1d

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/39009487/213038016-5de4d017-f792-435e-b044-47170486c1e9.png">

<img width="610" alt="image" src="https://user-images.githubusercontent.com/39009487/213038052-354b0058-7a93-41e1-abbb-cb90b2554f51.png">

want to confirm this closed @simonhac

**Comment by nc9** [comment]
@simonhac confirm for close

**Comment by simonhac** [comment]
the monthly emissions data looks bogus for periods like dec 2014 and pre 2009. @nc9 can you please regenerate it before i close this off?

**Comment by nc9** [comment]
they're running now its up to `2012`

**Comment by nc9** [comment]
the fix here impacted #185 - there is some logical inconsistency with the TAS1 interconnector
