### ISSUE TITLE
Latest interval in monthly aggregate data used in Stripes is 0

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#145]
![image](https://user-images.githubusercontent.com/39009487/198285814-2f73942e-b946-4cf3-9d5e-f9c9350237ea.png)

Check last month series in monthly and weekly aggregate outputs that are used in Stripes

**Comment by nc9** [comment]
Related #139

**Comment by simonhac** [comment]
at this moment, monthly is fine, but the daily has a 0 for today:

![Image](https://user-images.githubusercontent.com/20500649/208593640-a9177760-64cd-4031-92a2-fd370de593dd.png)


looking at `solar_rooftop` in `daily.json` i see that the last 9 entries are all `0`… clearly wrong.

**Comment by simonhac** [comment]
this is happening again:

![Image](https://user-images.githubusercontent.com/20500649/209260980-1f07e59a-b915-4c3c-aae2-1108a2da105a.png)

**Comment by nc9** [comment]
Test comment
