### ISSUE TITLE
Summated "All Regions" (NEM + SWIS) values not adding up

### ISSUE THREAD

**Issue by jufemaiz** [opennem/opennem#15]
From: https://twitter.com/yestiseye/status/1423481441535496193

The following approach was used to generate files for each generator type to compare and contrast, and data output included:

[github.com/jufemaiz/opennem-15](https://github.com/jufemaiz/opennem-15)

Assumptions is that, while different timezones are in use (UTC+10:00 for NEM and UTC+08:00 for SWIS) all other definitions of time (leading edge / falling edge of the period) are consistent between the two regions on Opennem (to ensure consistency).

For Solar (as raised above) please see:

* https://github.com/jufemaiz/opennem-15/blob/main/output/solar_rooftop_mw.csv
* https://github.com/jufemaiz/opennem-15/blob/main/output/solar_utility_mw.csv

**Comment by nc9** [comment]
This was actually a regression - i've written some unit tests to check pretty much along the same lines as what you have in that rb file.

**Comment by jufemaiz** [comment]
Any chance you could point to where to help better understand the codebase?

**Comment by nc9** [comment]
It's this query here - where it passes a list of network codes:

https://github.com/opennem/opennem/blob/master/opennem/api/export/queries.py#L484

that just goes back out to stats_factory which generates the JSON. In theory that query works with one network or a list of networks but I'm writing more tests around it

**Comment by nc9** [comment]
Have a look at 

https://github.com/opennem/opennem/blob/master/notebooks/check_all_regions_query.ipynb

for a comp of the outputs in a notebook - the rounding errors are because of the sigfig method used in the API outputs that rounds

**Comment by jufemaiz** [comment]
Erm https://github.com/opennem/opennem/commit/8157129a0fcd35d38b4d1b1b67fa9e806463eb9b doesn't actually provide details of the code that resolved this?

**Comment by nc9** [comment]
@jufemaiz I should have noticed this earlier - see #76 and https://github.com/opennem/opennem/commit/0861e4dddb353f057bc9143a7710dc64df5d71ac
