### ISSUE TITLE
'Emission Factor Per Network Region' API is returning 'No results' ERROR-422

### ISSUE THREAD

**Issue by Naveen-Karanamu** [opennem/opennem#154]
The GET 'Emission Factor Per Network Region' API expects an HTTP request from 'https://api.opennem.org.au/stats/emissionfactor/network/{network_code}' 

For which I am passing the {network_code} parameter that I got from the API call from 'https://api.opennem.org.au/networks' and passing the 'interval' query at the end but getting the output as 'No results', "response_status": "ERROR".

Please look into this and kindly let me know if I am missing something.
I am using python & it's libraries for making the API call as follows : 

- Input 
```bash
import requests
import json
url = 'https://api.opennem.org.au/stats/emissionfactor/network/NEM?interval=30m'
resp = requests.get(url).json()
print(json.dumps(resp, indent = 2))
```

- Output
```bash
{
  "version": "3.11.9",
  "created_at": "2022-11-10T18:17:49",
  "response_status": "ERROR",
  "detail": "No results"
}
```

**Comment by nc9** [comment]
This is related to #160 

We are changing the way we calculate emission intensities to do it per-interval using our aggregate tables and our own net-flow method. I will hook the API back up to these results

**Comment by Naveen-Karanamu** [comment]
> 

Okay, Thanks.
