### ISSUE TITLE
'Get energy output for a station' API is not able to fetch the data for the 'interval' of 'minutes' ERROR-500

### ISSUE THREAD

**Issue by Naveen-Karanamu** [opennem/opennem#155]
The GET request for the API 'Get energy output for a station'  in the 'interval' of minutes (let's say '5m), is returning the "INTERNAL SERVER ERROR". I am making the HTTP request for the API using the url 'https://api.opennem.org.au/stats/energy/station/{network_code}/{station_code}?period={period}&interval={interval}' 

I am fetching the parameter's 'network_code' & 'station_code' from the API GET request of 'https://api.opennem.org.au/station/'. One of the sample url for which I am getting the ERROR is "https://api.opennem.org.au/stats/energy/station/NEM/BHWF?period=7d&interval=5m". You can directly test this url in the browser.

Please look into this and kindly let me know if I am missing something. I tried to fetch the data using Python & it's Modules in the following manner: 

* Input 
```bash
import requests
import json
url="https://api.opennem.org.au/stats/energy/station/NEM/BHWF?period=7d&interval=5m"
station_energy_resp = requests.get(url).json()
print(json.dumps(station_energy_resp, indent = 2)) 
```

* Output
```bash
JSONDecodeError                           Traceback (most recent call last)
[<ipython-input-3-82e1b41a2394>](https://localhost:8080/#) in <module>
     16 
     17 url="https://api.opennem.org.au/stats/energy/station/NEM/BHWF?period=7d&interval=5m"
---> 18 station_energy_resp = requests.get(url).json()
     19 print(json.dumps(station_energy_resp, indent = 2))

3 frames
[/usr/lib/python3.7/json/decoder.py](https://localhost:8080/#) in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nc9** [comment]
Thanks for reporting this - I will be taking a look at it today

**Comment by nc9** [comment]
It sends a better error message now - we calculate energy per hour so the minimum interval size is `1h`

If you would like the data to be more current or granular - you can use the `/power/station/{station_code}` endpoint and just `/ 12` for energy or run your own calc

**Comment by Naveen-Karanamu** [comment]
> 

Got it. Thanks for the help.

**Comment by ujjwalmah** [comment]
Issue 1: For calculating 30 minutes interval from the 5 minutes interval that we are getting from the API : “https://api.opennem.org.au/stats/power/station/{network_code}/{station_code}”


If we do the same, try to compare the data of 5 min interval with the 30 min interval for 7 days time period, the data plot of 30 min interval should have higher values than that of the 5 min. The detailed explanation is below.
![image](https://user-images.githubusercontent.com/83815098/205435571-7a72e1b3-3bde-4bc7-938b-a7b4dee473bc.png)


If we take 12 values each of 5 minute interval [10,20,30,40,10,20,50,60,70,80,30,20] which is a total of 12*5=60 minutes interval of data. And plot it, we get:
![image](https://user-images.githubusercontent.com/83815098/205435589-3db29938-fd08-4c12-9a8c-7eac8511ab8a.png)


Here the highest value is 80, but when we plot the graph for the same in 30 minute interval  i,e. 6 (5 minutes data points together) : 6*5=30. So
[10 + 20 + 30 + 40 + 10 + 20] =130 for (1st 30 minutes) and 
[50 + 60 + 70 + 80 + 30 + 20] = 310 for (2nd 30 minutes)

When we plot this, we get:

Here the highest value will be 310 as we got this by combining the 2nd slot to 6*5 minutes data’s.

But when we look into the OpenNEM’s graphs, the highest point’s of both the graph’s lies around 170’s MW. But actually the 30 minutes interval graph values should be higher.

 Moreover, where the 30 minute interval graph’s values should be higher than the 5 minutes interval graphs values, we can see that, the case is reverse in the openNEM.

This is the graph generation of OpenNEM’s for Ararat station
For 5 minutes interval :
![image](https://user-images.githubusercontent.com/83815098/205435604-1c46a122-8c5f-4043-b847-ba634d631018.png)


For 30 minutes interval : 
![image](https://user-images.githubusercontent.com/83815098/205435615-0000a1e3-c984-44d8-9291-66d97e6a7b11.png)

**Comment by ujjwalmah** [comment]
> It sends a better error message now - we calculate energy per hour so the minimum interval size is `1h`
> 
> If you would like the data to be more current or granular - you can use the `/power/station/{station_code}` endpoint and just `/ 12` for energy or run your own calc

Issue 1: For calculating 30 minutes interval from the 5 minutes interval that we are getting from the API : “https://api.opennem.org.au/stats/power/station/{network_code}/{station_code}”


If we do the same, try to compare the data of 5 min interval with the 30 min interval for 7 days time period, the data plot of 30 min interval should have higher values than that of the 5 min. The detailed explanation is below.
![image](https://user-images.githubusercontent.com/83815098/205435571-7a72e1b3-3bde-4bc7-938b-a7b4dee473bc.png)


If we take 12 values each of 5 minute interval [10,20,30,40,10,20,50,60,70,80,30,20] which is a total of 12*5=60 minutes interval of data. And plot it, we get:
![image](https://user-images.githubusercontent.com/83815098/205435589-3db29938-fd08-4c12-9a8c-7eac8511ab8a.png)


Here the highest value is 80, but when we plot the graph for the same in 30 minute interval  i,e. 6 (5 minutes data points together) : 6*5=30. So
[10 + 20 + 30 + 40 + 10 + 20] =130 for (1st 30 minutes) and 
[50 + 60 + 70 + 80 + 30 + 20] = 310 for (2nd 30 minutes)

When we plot this, we get:

Here the highest value will be 310 as we got this by combining the 2nd slot to 6*5 minutes data’s.

But when we look into the OpenNEM’s graphs, the highest point’s of both the graph’s lies around 170’s MW. But actually the 30 minutes interval graph values should be higher.

 Moreover, where the 30 minute interval graph’s values should be higher than the 5 minutes interval graphs values, we can see that, the case is reverse in the openNEM.

This is the graph generation of OpenNEM’s for Ararat station
For 5 minutes interval :
![image](https://user-images.githubusercontent.com/83815098/205435604-1c46a122-8c5f-4043-b847-ba634d631018.png)


For 30 minutes interval : 
![image](https://user-images.githubusercontent.com/83815098/205435615-0000a1e3-c984-44d8-9291-66d97e6a7b11.png)
