### ISSUE TITLE
Bad gap-filling on SWIS rooftop

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#156]
![image](https://user-images.githubusercontent.com/39009487/201798238-377e2203-e5f1-45e1-8644-9d3b73c5921d.png)

**Comment by simonhac** [comment]
lots of data is missing and we appear to be gapfilling. 
<img width="234" alt="image" src="https://user-images.githubusercontent.com/20500649/201800296-4be85a36-7122-420c-96c0-b995f234e477.png">

**Comment by simonhac** [comment]
i think we shouldn't gapfill any solar data across 30 minute boundaries on the FE.

**Comment by nc9** [comment]
@chienleng I think the FE should should none here when it's empty

I just re-ran the old APVI endpoint and it has those values again.

**Comment by nc9** [comment]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/39009487/201806657-b2ac1eeb-04cf-4c4f-b0ad-099ac56f6181.png">

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/39009487/201806691-d1fb3a3a-a431-436e-8a7d-e89a7fa169cb.png">

**Comment by nc9** [comment]
https://twitter.com/OpenNem/status/1592334328780161024

**Comment by nc9** [comment]
I'll leave this open even with that patch above. The data seems to shift from underneath us

APVI returns no interval timestamp for periods that are assumed to be 0 - the SQL out is casting those to 0 now

**Comment by nc9** [comment]
I'm going to open another issue with APVI data issues - I've got a monitoring script now and some sanity-checks

**Comment by andrewbusch7** [comment]
![image](https://user-images.githubusercontent.com/6486627/205765579-a6329fc5-f1b6-4187-bd19-43be88a3ff31.png)
Quite a major one from 1 Dec 4 PM through to 3 Dec 4 AM. That's some pretty bold gap-filling, I too would prefer seeing zeroes in such cases. Could do the linear gap fill only if values are on the same day for solar, and otherwise zero.

**Comment by nc9** [comment]
> That's some pretty bold gap-filling,

I believe that is less gap-filling and more graphing the line down to the next data point



> I too would prefer seeing zeroes in such cases

100% agree. I have a changeset for this weeks release for this case

**Comment by nc9** [comment]
https://opennem.org.au/energy/wem/?range=7d&interval=30m

We eventually got complete data from APVI but this is more about how we handle cases where it fails

**Comment by simonhac** [comment]
@nc9 what did you actually do to fix this? the underlying cause, if i recall correctly was twofold:
* FE interpolates when it shouldn't. did we fix this?
* data doesn't differentiate between 0 MW and missing data.
