### ISSUE TITLE
Temperature Data is Misaligned to date

### ISSUE THREAD

**Issue by rob-ioenegy** [opennem/opennem#16]
I noticed when using the 1 Year View in days that the temperature data is mismatched.
I was looking at data for SA and noticed higher demand one 22 July. Looked at weather and saw the 23 July (Friday) was lower demand but much colder which seemed odd. I checked BoM and confirmed that the temps shown on OpenNem for 23rd were in fact the dat for 22nd.

**Comment by nc9** [comment]
ACK - fix is in this weeks release. Thanks.
