### ISSUE TITLE
Supply stack artefacts when interconnectors swing

### ISSUE THREAD

**Issue by aonaus** [opennem/opennem#160]
I'm sure you've noticed that the 5 minute stacked source charts for regions show "spike" artefacts when there's a rapid change in net imports / exports - a few examples here from Sunday 30 - Monday 31 Oct:

<img width="796" alt="OpenNEM 5m" src="https://user-images.githubusercontent.com/117059530/198933095-fe31f9b2-b4ea-4404-9d27-9d5437c46d78.png">

I suspect the reason for this will be that net imports / exports are being determined from the NETINTERCHANGE field in the MMS dataset (table DISPATCHREGIONSUM) while the generation and load values are SCADA metered power data, probably from DISPATCH_SCADA. The latter values are start-of-dispatch interval <b>actual readings</b>, whereas NETINTERCHANGE is an end-of-interval <b>target</b>. So this means that

- the generation/load and net import/export values are 5 minutes out of step with each other, and
- as a target value, NETINTERCHANGE doesn't capture the impact of dispatch deviations away from the scheduled solution (eg demand forecast inaccuracy, generator trips etc)

Both these differences can separately lead to the sort of "spike" artefacts highlighted above.

Unfortunately there's no single "like-for-like" data field corresponding with NETINTERCHANGE but giving a <b>start-of-interval actual</b> net import/export value. You would have to derive a net total for each region from the start-of-interval METEREDMWFLOW fields in table DISPATCHINTERCONNECTORRES records for the relevant interconnectors , applying the appropriate sign conventions. So for NSW net imports would be given by
METEREDMWFLOW (where INTERCONNECTORID = "VIC1-NSW1") [VNI]
minus METEREDMWFLOW (where INTERCONNECTORID = "NSW1-QLD1") [QNI]
minus METEREDMWFLOW (where INTERCONNECTORID = "N-Q-MNSP1") [Directlink]

**Comment by nc9** [comment]
@aonaus I just committed an update for this issue. We were calculating net flows (along with emissions and market value) each day for our energy outputs, but I have now updated it to run per-interval, so our power series on OpenNEM will show this calculation for imports/exports and also have emission intensity available as live data

The preview will be up on dev.opennem.org.au sometime over the weekend once this build is done - I'll keep this issue updated

**Comment by aonaus** [comment]
Awesome. Thanks for that Nik, will watch with interest.

**Comment by nc9** [comment]
This is now behind a feature flag as a part of v3.12

It is live on

https://dev.opennem.org.au/

**Comment by aonaus** [comment]
Nick

Thanks, looking at DEV, it seems to have worked but rooftop PV for
yesterday is missing there as well as some interconnector data from about
22:40 last night?

[image: image.png]

same period on live opennem

[image: image.png]

Allan

**Comment by nc9** [comment]
nemweb appears to have been delayed on rooftop data yesterday, our gap filling has resolved that once it was available again

I believe the interconnector data is complete at the moment, but I am taking a look right now
