### ISSUE TITLE
Energy Sums null values for NEM for 2011-2017

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#163]
![image](https://user-images.githubusercontent.com/39009487/203898820-6433565c-1896-43a0-8738-86c759068e02.png)

Energy sum values nulled out for 2011-2017

**Comment by nc9** [comment]
metadata on facility_scada shows last_updated in April this year.

metadata on aggregate table shows last updated this morning

**Comment by simonhac** [comment]
how does double counting happen?

![image](https://user-images.githubusercontent.com/20500649/203916147-5efbe4e2-dc84-4266-b38d-27410a351d9c.png)

**Comment by nc9** [comment]
> how does double counting happen?

I put in a fallback so that if energy sums don't exist it does `generated / network.intervals_per_hour` in this case it was adding both as `energy_sum` ran
