### ISSUE TITLE
Process timing module and method decorator

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#167]
Want to time backend processes and track start, end and completion time

- [x] for each process in the scheduler log start and end date
- [x] implement a decorator `opennem.core.profiler`
- [x] track process start/end dates in database
- [x] for slack alerts out include completion time
- [ ] track and trace SQL time vs CPU time

**Comment by simonhac** [comment]
i cheekily upped this to urgent because i want to see it in the monitoring logs!

**Comment by nc9** [comment]
This is now behind a feature flag as a part of `v3.12` 

It is live on 

https://dev.opennem.org.au

**Comment by nc9** [comment]
core module is done - any other changes I'll add as fixes on `v3.13`
