### ISSUE TITLE
Daily Solar Rooftop Aggregates Migrate from AEMO Backfill to APVI Data

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#171]
`AEMO_ROOFTOP_BACKFILL` is a network that contains derived data to populate `solar_rooftop` data prior to the AEMO source start date.

The data is currently bucketed in months at the beginning of each month, we need to source at a minimum daily data, preferably per-interval data

This issue stands out on the FE when you look at stripes:

https://opennem.org.au/stripes/nsw1/?metric=solarProportion

And see the 'pillars of midnight flashes' in the data:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/39009487/206052494-ff4998cd-0cf1-4ad2-a2e8-0703c110643e.png">

Tasks:

- [x] Find/investigate original source of data and when / how it was imported
- [x] Temporarily disable `AEMO_ROOFTOP_BACKFILL` in daily outputs 
- [x] What is the interval size of the source, are there alternate sources? (APVI extends back to 2016)
- [x] Correct / import
- [x] Re-run weeklies in archive, daily outputs once in and re-enable
- [ ] Document what data is loaded from where, how it is generated
- [x] Trailing zeros ( #156 related )

**Comment by simonhac** [comment]
according to @dylanjmcconnell, APVI extends back to may 2013.

let's start by limiting _daily_ data series to:
* all APVI from may 2013 to nov 2016
* all AEMO rooftop solar from 2016

…but keep the pre-may 2013 monthly backfill data (which dylan estimated) in the _monthly_ series.

**Comment by nc9** [comment]
On dev with APVI data:

https://dev.opennem.org.au/stripes/nsw1/?metric=solarProportion

**Comment by simonhac** [comment]
…also fix trailing zeros.
