### ISSUE TITLE
Tracking stopped at 1am 30/12?

### ISSUE THREAD

**Issue by ikt** [opennem/opennem#178]
Hi team, looks like the tracking stopped this morning at 1am? Not sure if bug or normal, thanks!

Thank you for your work on this project as well, it's amazing

**Comment by nc9** [comment]
Our connection to nemweb at AEMO is down - working on this at the moment

**Comment by nc9** [comment]
we're back at the latest interval of data from AEMO - really funky interconnect issue between AWS -> nemweb

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/39009487/210033298-8c21b97c-a23d-4b5c-8079-e45e77ad5081.png">

I'll leave this open for now as I'm keeping an eye on it
