### ISSUE TITLE
Staging Environment

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#181]
Create an OpenNEM staging environment with dev/rc releases on production data

- [x] basebackup of prod database onto staging server
- [x] setup docker stack on staging server
- [x] `monitoring-staging` slack channel 
- [x] separate environment in settings, configs, sentry etc.
- [x] setup subdomains and hosts names
- [x] setup s3 bucket for `staging.data.opennem.org.au`
- [x] write out all outputs into buckets
- ~~adapt FE for separate environment~~

**Comment by nc9** [comment]
cc @chienleng

**Comment by chienleng** [comment]
Going to split this ticket. BE is done and I'd like the FE to work like feature branches (auto build and deploy).

**Comment by chienleng** [comment]
FE ticket: https://github.com/opennem/opennem-fe/issues/212
