### ISSUE TITLE
stripes data: huge jump in rooftop solar between nov '21 and dec '21

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#182]
![image](https://user-images.githubusercontent.com/20500649/213036689-391e52b5-ceb7-4187-b157-12b691608deb.png). 
![image](https://user-images.githubusercontent.com/20500649/213036716-af308024-a0f0-4e35-b63a-47d6c123087e.png)

you can see the jump in `au.nem.sa1.fuel_tech.solar_rooftop.energy` in [monthly.json](https://data.opennem.org.au/v3/stats/au/all/monthly.json)
![image](https://user-images.githubusercontent.com/20500649/213036930-26d73fe8-7c54-4fe4-8638-27728774839c.png)

**Comment by simonhac** [comment]
oddly the numbers are similar, but different to data in [all.json](https://data.opennem.org.au/v3/stats/au/NEM/SA1/energy/all.json)

from `au.nem.sa1.fuel_tech.solar_rooftop.energy`:
![image](https://user-images.githubusercontent.com/20500649/213037578-206a16a1-bf29-4e09-abdb-957dfcc172ad.png)

nb. 212 values in all.json, 288 values in monthly.json (above).

**Comment by nc9** [comment]
the `all.json` on prod would be a bit out of date from before a lot of fixes and integrating the APVI data

**Comment by simonhac** [comment]
`all.json` was generated at `2023-01-18T06:37:25+10:00` — this morning. how can it be out of date?

a few things:
1. why are the numbers different (between the two data files) for recent SA data?
2. why do the number of data points differ?
3. why the significant jump in order of magnitude in `monthly.json`?

**Comment by simonhac** [comment]
also, the `created_at` time in `monthly.json` is missing a timezone:

![image](https://user-images.githubusercontent.com/20500649/213054693-97b42f5a-2c55-42fd-8285-c58ce9885da5.png)

**Comment by nc9** [comment]
ready to validate

https://dev.opennem.org.au/stripes/nem/?metric=solarProportion

**Comment by simonhac** [comment]
sorry, still broken @nc9.


<!-- Uploading "image.png"... -→

**Comment by nc9** [comment]
![image](https://user-images.githubusercontent.com/39009487/226207076-7bb62db1-1a92-48b6-bc5b-b40ff8d60476.png)

**Comment by nc9** [comment]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/39009487/226494942-5449c357-9727-496d-9f8c-983b459701cc.png">

on prod

**Comment by nc9** [comment]
@simonhac I want to merge #183 and #206 into here and track it as one issue, which is essentialy:

 * make all rooftop energy outputs consistent across stripes / energy by aggregating `AEMO_ROOFTOP` and `OPENNEM_ROOFTOP_BACKFILL`

This is currently the state on dev right now

**Comment by gmmspi** [comment]
1. AEMO
2. APVI
3. DYLAN

**Comment by simonhac** [comment]
looks good on dev.
