### ISSUE TITLE
stripes data: missing au.*.fuel_tech.solar_rooftop.market_value

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#183]
we have `au.nem.sa1.fuel_tech.solar_utility.energy` and `au.nem.sa1.fuel_tech.solar_utility.market_value`.

we have `au.nem.sa1.fuel_tech.solar_rooftop.energy` but _not_ `au.nem.sa1.fuel_tech.solar_rooftop.market_value`.

![image](https://user-images.githubusercontent.com/20500649/213038254-427f252b-8149-46eb-8e62-9efb82005063.png)

**Comment by simonhac** [comment]
i suspect this is why we're seeing big blocks of $0 values:
![image](https://user-images.githubusercontent.com/20500649/213038626-3a152e45-c9f5-4f37-9bf0-bb3b1be6b62f.png)

**Comment by simonhac** [comment]
…any why @chienleng is outputting this:
![image](https://user-images.githubusercontent.com/20500649/213038714-43530885-e7ad-4b59-b8ae-ed7025cf91aa.png)

**Comment by nc9** [comment]
![image](https://user-images.githubusercontent.com/39009487/226207221-be04fde7-22e6-4d1a-940e-0b41fbf58f7f.png)

**Comment by nc9** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/39009487/226494992-26ca211b-fcee-45dc-9a87-25d106aa3238.png">

on prod

**Comment by simonhac** [comment]
as per #206, we're missing data from before 2015-03. not ready to close.

**Comment by simonhac** [comment]
looks good on dev… except for the missing data before 2015-03.
