### ISSUE TITLE
SA import/export emissions are borked… flipped?

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#185]
SA's imports come from victoria, which has an average grid intensity of ~850 kgCO₂e/MWh.

SA's exports are generally when the state is pumping out renewables, so we'd expect a low (sub-200?) emissions intensity for exports.

could these have been inadvertently swapped?

![image](https://user-images.githubusercontent.com/20500649/213066495-2978d046-6496-4523-8cf2-1a0fe60cb1cb.png)

**Comment by simonhac** [comment]
super urgent that we fix… and ensure that this is not a problem with any other region.

**Comment by simonhac** [comment]
thanks. please ping me on slack when SA and TAS are ready to check.

**Comment by simonhac** [comment]
@nc9 my test comment worked!

**Comment by nc9** [comment]
its back - will work on this in #144
