### ISSUE TITLE
Several WCMG facilities showing no generation

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#186]
tim noticed:

> there appears to be a really high number of facilities where no generation data is available, even if you change the view over to show all-time generation. I think like 2 out of 10 worked

![image](https://user-images.githubusercontent.com/20500649/213643786-2807766e-21db-46e3-a0be-26f96443c303.png)
![image](https://user-images.githubusercontent.com/20500649/213643805-db23a4de-6828-4ea3-9415-c5959222871d.png)
![image](https://user-images.githubusercontent.com/20500649/213643822-1b7e8d0d-e569-4682-84d6-66bc9b16a6ed.png)
![image](https://user-images.githubusercontent.com/20500649/213643837-a6cd30f8-ffa1-457d-8736-08ed7197d896.png)

**Comment by nc9** [comment]
#122 likely related

**Comment by nc9** [comment]
https://gist.github.com/nc9/4d8a12be48387d1bf588d58a573caf9d

**Comment by nc9** [comment]
see #190 merged into there
