### ISSUE TITLE
Update CPI series

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#187]
CPI series currently ends on `2021-03-31T10:00:00+10:00` with value `117.9`.

from ABS series `6401.0 Consumer Price Index, Australia`, SeriesID: `A2325846C`:

Quarter ending | Value
-- | --
31-Mar-2021 | 117.9
30-Jun-2021 | 118.8
30-Sep-2021 | 119.7
31-Dec-2021 | 121.3
31-Mar-2022 | 123.9
30-Jun-2022 | 126.1
30-Sep-2022 | 128.4
31-Dec-2022 | 130.8

**Comment by simonhac** [comment]
just realised this data comes from the backend — moving to the correct repository.

**Comment by simonhac** [comment]
@nc9 i thought i'd have a crack at editing `opennem/data/au_cpi.json` but i suspect that's not the source any more.

the last entry in [au_cpi.json](https://github.com/opennem/opennem/blob/master/opennem/data/au_cpi.json) is `2020-09-30T00:00:00`.
however the last entry in [monthly.json](https://data.opennem.org.au/v3/stats/au/all/monthly.json) corresponds with `2021-03-31T10:00:00+10:00` — 2 quarters later — so there must be another source.

can you please look into this?

**Comment by nc9** [comment]
https://github.com/opennem/opennem/blob/master/opennem/data/au_cpi.json#L2419
