### ISSUE TITLE
Tighten up fetching of overnight files

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#189]
[Next_Day_Actual_Gen](https://www.nemweb.com.au/Reports/CURRENT/Next_Day_Actual_Gen/) files are being fetched at strange times. going backwards over the last few days: 7.12am, 6.25pm, 8.20pm, 1.24am, 6.28pm, 8.28am…

the files generally come out at around 4.10am, rarely more than 2 minutes afterwards.

i suspect we have a generic mechanism for fetching periodically published files. it should take retry parameters, and aim to minimise the interval between publishing and fetching without putting undue load on the file host.

in this case, we could poll at 4:10:00 and poll again with backoff intervals something like:
* every 15 seconds for 12 attempts (taking us to 4:13:00)
* every 60 seconds for 12 attempts (taking us to 4:30)
* every 300 seconds thereafter, until the task expires

on _most days_ the host would be hit less than half a dozen times, and we'd have data less than 15 seconds of it being published.

**Comment by nc9** [comment]
based on the benchmark script I believe I have a better timer now .. I'm going to merge it in

**Comment by simonhac** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/20500649/221338121-6c1c211f-d001-4c0c-b869-5810492dcae0.png">

~6.5 hours to process the overnight records — given this finished at 8.47am, it must have started at ~2.15am.

i thought it couldn’t start before 4am?

**Comment by simonhac** [comment]
also, the day should be `2023-02-24`, not `2023-02-24 04:00:00+10:00`.
