### ISSUE TITLE
Clean up profiler logging to slack

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#197]
Current profile messages in slack are messy. We have ~42 methods where profile information is persisted and optionally logged to slack.

![image](https://user-images.githubusercontent.com/39009487/220232105-38bcc5ca-f478-4162-a579-0a47cc0e6198.png)

Need to clean up the slack logging format:

For the profiler:

- [x] Change custom message format to be an append of additional context from `locals()` and `args**` simplifying it (no completely custom logging)
- [x] Strip out the generic `method(argument)` log types to slack
- [x] Remove invoke, persist and other parameters 

For interval messages for each network:

- [x] Network alias first 
- [x] Interval time, not fetch or dirlisting modified time
- [x] Log errors on none values
- [x] Bubble up values from the WEM clients so that they're accessible to the profiler

Example per-interval output:

```
[development] NEM new interval for 2022-02-21 13:20 stored 671 records in 32.0s
```

**Comment by simonhac** [comment]
@nc9 can you please change this:

> [development] New NEM dispatch data for interval `2023-02-22 09:15:00+10:00` with `422` inserted records and updated flow tasks

to something very close to this:

> [development] NEM: `task_name` processed 422 new records for interval `2023-02-22 09:15:00+10:00` (42s)

**Comment by nc9** [comment]
ACK you'll see exactly that format in the next push

**Comment by nc9** [comment]
via @simonhac 

looks much better… but please tweak: drop decimal place in time and place and change highlighting:

```
[development] NEM per_interval pipeline processed 423 new records for interval 2023-02-23 21:25:00+10:00  (96s)
```

**Comment by simonhac** [comment]
@nc9 i'll close this issue when i see the formats of these 3 line types harmonised.
<!-- Uploading "image.png"... -→

**Comment by simonhac** [comment]
great progress — thanks @nc9!
