### ISSUE TITLE
stripes data: au.nem.*.fuel_tech.solar_rooftop.energy missing data before 2018-03-01

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#206]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/20500649/221340188-6d27f4a1-8718-4b5f-9adc-18f7648bddde.png">

this is very evident in stripes:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/20500649/221340225-16218155-e689-4c7a-814d-2fd78d8f5949.png">

**Comment by nc9** [comment]
ready to validate 

https://dev.opennem.org.au/stripes/nem/?metric=solarProportion

**Comment by simonhac** [comment]
nope, still missing:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/20500649/225488339-4191ac17-5a46-45d2-80c1-a1d4756ce4d8.png">


this is from [`monthly.json` on dev](https://data.dev.opennem.org.au/v3/stats/au/all/monthly.json)
<img width="318" alt="image" src="https://user-images.githubusercontent.com/20500649/225488382-b4c15eea-48fb-4973-b6be-97c353b08ffc.png">

**Comment by nc9** [comment]
#182 is the same fix on dev now

**Comment by simonhac** [comment]
good that we now have from 2015-03 to 2018-03 loaded, but we're still missing rooftop solar before 2015-03.

it's in the energy view, but not stripes view:
<!-- Uploading "image.png"... -→

**Comment by nc9** [comment]
@simonhac consisted daily/monthly buckets between stripes/energy/fac out on dev rn

merging #182 into here

**Comment by gmmspi** [comment]
This doesn't look right to me @nc9 

Price data and stripes goes back to June 09 but the energy graph has no data til 2015

![Image](https://user-images.githubusercontent.com/126639348/230277760-92eed908-8cbc-4301-89e4-49610c586630.png)

**Comment by simonhac** [comment]
hmmmm… TIL the price chart does not respond to the selection. emissions does, price doesn't.

https://user-images.githubusercontent.com/20500649/230286059-a1260ac4-b2ef-4094-b326-003a12b62e22.mov

this is really a front end issue.

**Comment by simonhac** [comment]
…and a bit tricky. for accurate VWP i believe we use `*. au.nem.demand.energy` for the denominator.

so i think we need two modes:
• if any series is deselected: sum the generation
• otherwise, use `*. au.nem.demand.energy`.

**Comment by gmmspi** [comment]
I'll create a new FE issue for that.

Back to the issue at hand, in Simon's comment above (https://github.com/opennem/opennem/issues/206#issuecomment-1477157893) there looks to be energy data back to 2009 but I now see energy data only going back to 2013. Is this intentional?

**Comment by nc9** [comment]
![image](https://user-images.githubusercontent.com/39009487/231599963-479a16ed-320a-4c93-ab5f-68a45ae5d643.png)

ondev

**Comment by gmmspi** [comment]
Still seeing some issues here. EG - in All Regions view I see data for this fuel tech in Queensland in June 2011. In Queensland view, I see no data. 

![Image](https://user-images.githubusercontent.com/126639348/233871504-e8788c7e-5ccf-49b2-a58a-af4fd198843d.png)


![Image](https://user-images.githubusercontent.com/126639348/233871509-79f77997-a3dc-4618-9363-64a5ad51437a.png)

**Comment by gmmspi** [comment]
This is by design, no daily bucket data going back that far.
