### ISSUE TITLE
Missing imports/exports January – June 2009

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#208]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/20500649/221393676-9985b51d-45ca-4e04-8ce4-ad622554b8f6.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/20500649/221393689-b0109f4d-8a39-4c04-ad06-21dde7ce2bc9.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/20500649/221393695-b0463019-390c-44fd-a11d-0539efd1952d.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/20500649/221393699-f5128728-3f10-414e-93f8-f971529a09d8.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/20500649/221393705-6ca629d9-b1e1-4c65-aff9-e8a9fa4010fe.png">

**Comment by nc9** [comment]
On this first

**Comment by nc9** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/39009487/223890537-0d765206-0171-4132-bf37-cc0c61bf459e.png">

this is on dev

**Comment by simonhac** [comment]
still missing on all regions other than NSW.

**Comment by nc9** [comment]
I was using NSW1 as a test and left it in `init`

it's all updated now 

![image](https://user-images.githubusercontent.com/39009487/225457851-3caa297a-04ef-4aba-8d42-e9eae6883f30.png)

**Comment by simonhac** [comment]
thanks… looks good on dev @nc9. now for prod!

**Comment by nc9** [comment]
![image](https://user-images.githubusercontent.com/39009487/226211890-66d06edf-97f7-4521-af3f-45fce4f966b5.png)

it's on prod

**Comment by nc9** [comment]
@simonhac this one gets closed, right - emissions < 2009 are a separate issue
