### ISSUE TITLE
Separate Monitoring Stack

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#211]
We need to separate out the monitoring stack first which sends out alerts to Slack, Twilio and StatusPage as errors in the backend and performance degradation can affect monitoring

- [x] split out into separate repo / docker build
- [x] host on non-AWS (cloudflare)
- [x] setup hooks into slack, twilio alerts and statuspage

**Comment by nc9** [comment]
see issue from #229 on what we should cover

combine with 1-month test data in unit tests

**Comment by nc9** [comment]
#210 on monitoring as well

**Comment by nc9** [comment]
see https://github.com/opennem/monitoring

**Comment by gmmspi** [comment]
Design a new monitoring page that includes status page output and monitoring API output

**Comment by nc9** [comment]
closed - status page separate issue
