### ISSUE TITLE
Scheduling tasks on AWS

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#225]
Goal: replace `opennem.workers.scheduler` with an AWS-native process

API container will run on Fargate as of `v3.14` 

To replace the worker process, we have an option of:

* Using Fargate Tasks
* Using a Fargate process with it's own scheduler
* Running AWS Batch
* Running lambda tasks 

For each of these, evaluate:

* Granuality of being able to start tasks - we require strict on-minute interval checks for data ingress
* Retry and backoff policies available
* Running containerized workloads (Amazon is hopeless with updating Python environments - they're at 3.8 iirc, we're at 3.11)
* Costs 
* Benefit of edge tasks spreading IP address load (we tend to get blacklisted at the moment)

**Comment by gmmspi** [comment]
Useful background: https://awstip.com/how-to-run-aws-lambda-functions-every-few-seconds-82a3aaecb221

**Comment by gmmspi** [comment]
This might be the way: https://github.com/guiyom-e/cdk-scheduler
