### ISSUE TITLE
Issue with solar_rooftop value 

### ISSUE THREAD

**Issue by macbryla** [opennem/opennem#228]
I noticed a recent change (seems like an error) when calling 
https://data.opennem.org.au/v3/stats/au/NEM/power/7d.json

The last value in the 7d (30min) list in the "solar_rooftop", is always ZERO, 
e.g.
333:  1583
334:  2754
335:  0

There also seems to be a similar issue when calling 
https://data.opennem.org.au/v3/stats/au/AU/power/7d.json

This time the value is not ZERO, but it seems too small or ZERO.
e.g
333: 1582
334: 2758
335: 14.88

Must be some timing issue when these are updated.

As an aside, is this the best API to call for country wide 5min resolution. Just checking to make sure if there is a newer more approbate API to call.

Thank you for a great resource.

**Comment by nc9** [comment]
Thanks for reporting this - we have a fix in the pipeline that is going to be rolled out on prod today. Tracked at #216

**Comment by nc9** [comment]
@macbryla this is on our production systems now - thanks for the report! if there are any other issues please let us know and feel free to tag me

**Comment by macbryla** [comment]
There seems to be the same issue for rooftop solar for WEM
https://data.opennem.org.au/v3/stats/au/WEM/power/7d.json

Thanks @nc9

**Comment by nc9** [comment]
can you tell me what you're seeing? when I hit that output now it ends with a value - it might be a question of timing it. if you catch it again, can you screenshot the top of the response envelope so I can see the `created_at` please - I'll also keep an eye on it
