### ISSUE TITLE
Production Database Backups

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#231]
Currently, we're just dumping to disk on a corn task with `pg_dump` every Sunday and moving to the other server. 

Migrate to

- [ ] setup [pgBackRest](https://pgbackrest.org/) on `db`
- [ ] store a rolling copy of 3 full backups with daily incrememntals
- [ ] store encrypted on s3 into `backups.opennem.org.au` (a private bucket)
- [ ] don't sync outside of AWS into hot-standby because the transit fees are expensive++ (ugh)

In the case of needing a quick restore - we can bring up a standby on AWS

**Comment by gmmspi** [comment]
Awaiting configuration of write-ahead logs @nc9
