### ISSUE TITLE
Stripes: daily data ends on 2023-01-27, and with a bad value

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#233]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/20500649/226855069-2df3670f-3fe3-4f9e-b185-64c3d802017b.png">

**Comment by nc9** [comment]
This is an old version of the `json` - I'll figure out how it got there!

**Comment by nc9** [comment]
it's on dev :

https://dev.opennem.org.au/stripes/nsw1/?metric=renewablesProportion

**Comment by nc9** [comment]
@simonhac

**Comment by simonhac** [comment]
daily data looks good on dev.

**Comment by gmmspi** [comment]
Closing - looks good on prod

**Comment by nc9** [comment]
monthly buckets of data go further back, in daily aggregates we go back to 2015

it's described in 

https://github.com/opennem/opennem/wiki/Networks

we need to track down daily aggregate data back to the 0 value for rooftop, which can likely be provided by APVI
