### ISSUE TITLE
Updating facility_daily aggregates all is destroying data

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#234]
![image](https://user-images.githubusercontent.com/39009487/227383738-fa6a3353-f9b6-4870-ab3e-4650a0b00874.png)

this step in `upgrade-v3.14.py` is killing the range from `June 2013` - `Dec 2017` (with partials in each of those months):

```
    for network in [NetworkNEM, NetworkWEM, NetworkAEMORooftop, NetworkAPVI, NetworkOpenNEMRooftopBackfill]:
        run_aggregate_facility_all_by_year(network=network)
```

**Comment by gmmspi** [comment]
Closing - issue resolved on dev and prod
