### ISSUE TITLE
solar_utility start and end dates in stripes daily and monthly

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#240]
At the moment `NSW1` for `solar_utility` is padding out 14 `0` values and adding a year further back in the stripes view:

![image](https://user-images.githubusercontent.com/39009487/228689495-5c306381-3942-4284-80be-d3f6e0bf899c.png)

in the view:

![image](https://user-images.githubusercontent.com/39009487/228689634-785c8c8f-d768-49e3-80df-53bc3c872073.png)

should be trimmed back to the same start value for all regions 

use `TAS1` start date as the left-hand side trim-point, we want to show all zero values for solar that we know are 0

**Comment by simonhac** [comment]
probably should take all _utility_ data back to the date their region entered the NEM — this needs to be recorded on the wiki.

_rooftop_ data should only go back as far as dylan's estimated data.
