### ISSUE TITLE
Facility emissions total off by a factor of 12

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#244]
![image](https://user-images.githubusercontent.com/39009487/228990227-feddf163-fe58-470b-95cf-75b46de112e6.png)

**Comment by gmmspi** [comment]
Closing, looks good prod to me: GERMCRK emissions_factor of 0.62 matches up with the 255 MtCo2e for 411MWh of energy

![Image](https://user-images.githubusercontent.com/126639348/230284751-b3cafd12-734d-4593-b1c0-84fdfa980cf0.png)
