### ISSUE TITLE
Missing market_volume in facilities

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#256]
from [Liddell](https://opennem.org.au/facility/au/NEM/LIDDELL/?range=all&interval=1M)
<img width="450" alt="image" src="https://user-images.githubusercontent.com/20500649/230827213-8d836fd1-5991-4c8a-8011-929dbecb5c2a.png">

**Comment by nc9** [comment]
this was related to #234 and re-running it on prod, it's filling it now
