### ISSUE TITLE
Website and api not updating

### ISSUE THREAD

**Issue by macbryla** [opennem/opennem#267]
Where is the right place to report web and api update issues?
It seems both showing old data now, this screenshot was taken at 6pm.

<img width="1429" alt="Screenshot 2023-04-25 at 6 09 59 pm" src="https://user-images.githubusercontent.com/251217/234215983-b7385826-3ed4-424f-8781-ff26ab743a11.png">

**Comment by nc9** [comment]
yep - this is the right place! it's up to date now but i'll have a look at where the delay came from

**Comment by nc9** [comment]
we've added some healthchecks on the API endpoint but I believe this may have been a delay on some of our data sources - we're handling this a bit better #266 

Thanks again for reporting this
