### ISSUE TITLE
Facility geo updates from feedback - incorrect state/location

### ISSUE THREAD

**Issue by gmmspi** [opennem/opennem#284]
**Path:**
/facility/au/NEM/CBWWBA/?range=3d&interval=30m

**Sources:**
Map
**Fields:**
[
 {
  "key": "Facility satellite map",
  "value": {
   "type": "Point",
   "coordinates": [
    115.69424934340425,
    -30.680970908597665
   ]
  }
 },
 {
  "key": "Facility default map",
  "value": {
   "type": "Point",
   "coordinates": [
    115.69424934340425,
    -30.680970908597665
   ]
  }
 }
]

**Description:**
Says its in South aus, Map says otherwise

**Comment by nc9** [comment]
Christies Beach updated on dev:

https://dev.opennem.org.au/facility/au/NEM/CBWWBA/?range=1y&interval=1w
