### ISSUE TITLE
why are import average prices for imports usually negative?

### ISSUE THREAD

**Issue by aleith** [opennem/opennem#318]
Been looking at SA import and export prices and volumes for quarters and years etc. Usually the average price for imported energy  is negative. Sometimes exports are negative and more often (in most states anyhow) the prices are positive, but in SA exports are sometimes negative. Does a negative average reflect selling power is occurring, on average, at negative prices or is it a convention of OpenNEM to price imports as negatives, even when the purchasing price is positive? and vice versa?

Hope that makes sense, I'm at a lost as to how to interpret and what the accounting principle behind this is.

**Comment by nc9** [comment]
Hi @aleith  - apologies for the delay we've been under-resourced

This is an old legacy from the prev version of OpenNEM. 

We've already made this all consistent on dev but we need to sync the change with our own frontend and API consumers before 

Track #318 - and originally reported in #324

**Comment by nc9** [comment]
i'll point you to it once it is up :)

we're also are switching over all our infra (to railway.app if you're curious) so we have a lot on atm :)

**Comment by aleith** [comment]
you guys are constantly changing the backend support infrastructure! I can't keep up.

**Comment by nc9** [comment]
sorry! we're in the middle of a major migration from v3 to v4 - we messed up part of it for a moment.

v4 will have major breaking changes - you can see it on 

https://dev.opennem.org.au/

v3 should be going back to being consistent - we're trying _really_ hard to both grow the platform and retain backwards-compatability at the same time. It's been a bit of a pain.

Negative numbers in imports is a v4 feature - any last remnant of any part of it appearing in v3 (ie. prod) should be cleared by tonight / tomorrow latest

**Comment by aleith** [comment]
yeah i can image backwards compatibility is quite a pain refactoring so much code and adding so many features. take a leaf out of Apples book and ditch the old when it makes sense! social media posts only have a limited lifespan anyhow if that's the concern, ie breaking links.

**Comment by aleith** [comment]
the thing i'm really hanging out for so we can fork opennem into future scenario visualisation tool is to be able to inspect all the data from start date to end date in the set in the 1D, 5min and 30min modes. i've been wanting this for almost a decade now! i believe it's all been in the works for backend and front end for quite a long time, but not a a priority as it requires  significant refactoring — unlike some of the other FRs for new shining things.

**Comment by nc9** [comment]
@aleith i'm going to send you an API key for v4 first and you can see the new API. Having a fully open API just meant we kept getting hammered so I had to pull back the data we were returning. The amount of traffic was just too much.

With the new API we can control access and open up the entire data set

We also have a new feature coming by year-end where you can do custom queries against the entire data set - that's gonna be a bit of work, but I believe with that and combined with having the entire history of all data we'll be the best source

**Comment by aleith** [comment]
>  With the new API we can control access and open up the entire data set

Amazing!

> With the new API we can control access and open up the entire data set
We also have a new feature coming by year-end where you can do custom queries against the entire data set - that's gonna be a bit of work, but I believe with that and combined with having the entire history of all data we'll be the best source

Sounds really cool, thanks heaps for putting so much effort into these functions and refactoring to do it!
