### ISSUE TITLE
Inconsistency in number of datapoints returned

### ISSUE THREAD

**Issue by skovhus** [opennem/opennem#33]
Hi from [electricitymap.org](https://electricitymap.org). 👋 

While refetching some historical data, we observed some inconsistencies in the number of data points returned for some date times.

https://api.opennem.org.au/stats/flow/network/NEM?month=2017-01-01 correctly returns 8928 data points for the first data element `['data'][0]['history']['data']`, which matches with 2017-01-01 00:00:00+10:00-2017-01-31 23:55:00+10:00 and 5min buckets.

https://api.opennem.org.au/stats/flow/network/NEM?month=2017-10-01 only returns 8927 data points for the first data element. We observed multiple dates with this issue.

Currently, we discard the dates that contains these inconsistencies.

**Comment by nc9** [comment]
Hey there! ACK

> only returns 8927 data points for the first data element.

This shouldn't be happening as there is a Pydantic validator to check that the numbers match up on output otherwise it sends a ValidationError - but I'll take a look at this soon. Thanks for reporting it

**Comment by adriaan** [comment]
I'm seeing the same issue.

**Comment by nc9** [comment]
#129 is the validators that validate all responses
