### ISSUE TITLE
Internal server error (flow/network/NEM?month=2021-06-01)

### ISSUE THREAD

**Issue by skovhus** [opennem/opennem#34]
We experience some internal server errors when querying some API resources. Some examples:
- https://api.opennem.org.au/stats/flow/network/NEM?month=2021-05-01 
- https://api.opennem.org.au/stats/flow/network/NEM?month=2021-05-10
- https://api.opennem.org.au/stats/flow/network/NEM?month=2021-06-01

**Comment by nc9** [comment]
Saw this in our Sentry - will attach fix on this issue shortly - thanks

**Comment by nc9** [comment]
This is working on dev as of the new `3.7.10` release:

https://api.dev.opennem.org.au/stats/flow/network/NEM?month=2021-05-01

should be deployed sometime today.
