### ISSUE TITLE
Emails to github@opennem.org.au bounce

### ISSUE THREAD

**Issue by brandongalbraith** [opennem/opennem#4]
![Screen Shot 2020-09-13 at 12 06 02 PM](https://user-images.githubusercontent.com/350893/93022911-3bd43180-f5b1-11ea-8388-e5ac240a8db5.png)

**Comment by nc9** [comment]
Thanks for alerting us - we've never had the domain setup to accept emails but are doing so now!

**Comment by brandongalbraith** [comment]
No worries! I had attempted to email about Western Australia generation facility/capacity data no longer being available on the site (https://opennem.org.au/facilities/wa1/), but when I checked more recently, it was available again!

**Comment by nc9** [comment]
Ahh that's the new data we've been shaping! I'll have to include our contact details on the page somewhere

**Comment by nc9** [comment]
Thanks for the heads up - we forgot to move that alias when migrating to Google Workspaces
