### ISSUE TITLE
ElectricityMaps bugs and issues

### ISSUE THREAD

**Issue by simonhac** [opennem/opennem#40]
the [endpoint](https://data.opennem.org.au/v3/clients/em/latest.json) used by [electricity-map](https://app.electricitymap.org/map):

- returns `solar_utility` for NSW, QLD, VIC, SA, WEM (there is no utility solar in TAS) 
- returns `solar_rooftop` for WEM

but
- omits `solar_rooftop` for NSW, QLD, VIC, SA & TAS.

please add the `solar_rooftop` series for the 5 missing states.

this is resulting in rooftop solar being omitted from electricity-map, and making australia look even worse than it is!

**Comment by chalg** [comment]
Doesn't look like this is reflected on [electricity-map](https://app.electricitymap.org/zone/AUS-QLD) yet. Do they need to do something on their end?

**Comment by nc9** [comment]
@chalg it's on our dev - will be on our prod at some point in the next 24h

**Comment by simonhac** [comment]
doesn't look like it. when i hit the endpoint (`3.8.1-alpha.2`) the only solar i get is:
* au.nem.nsw1.fuel_tech.solar_utility.power
* au.nem.qld1.fuel_tech.solar_utility.power
* au.nem.vic1.fuel_tech.solar_utility.power
* au.nem.sa1.fuel_tech.solar_utility.power
* au.wem.fuel_tech.solar_utility.power
* au.wem.fuel_tech.solar_rooftop.power

ie. missing most rooftop.

**Comment by simonhac** [comment]
please don't close until rooftop solar is confirmed to be showing up on [electricity-map](https://app.electricitymap.org/map).

(i think they aggregate both `solar_rooftop` and `solar_utility` solar into just `solar`.)

**Comment by nc9** [comment]
ACK - I think I've regressed this somehow because I checked it. Will post tonight.

**Comment by pierresegonne** [comment]
Hey guys, Pierre from ElectricityMap. 

Quick investigation shows that your `latest` endpoint now provides solar rooftop data, but when querying past data (which we'd like to do to update previous data that did not account for solar rooftop), the field is not present. Would it be possible to enable historical data to have the solar rooftop category as well? 

Otherwise, the data we receive from you, from the `latest` endpoint, should account for solar rooftop, it is embedded with "normal" solar on the map. There is a slight issue with the parser that turns the values we receive to 0, but that should be fixed by tomorrow.

**Comment by nc9** [comment]
That's brilliant @pierresegonne thank you.

I have a few tasks that I'm working on today regarding the API endpoints, I'll check and move the same solution over for your archive feeds.

**Comment by nc9** [comment]
actually @pierresegonne just checking EM at the moment, it's showing 6% for NSW and similar which doesn't seem to include solar - we're showing ~40% at 10AM today

<img width="437" alt="Screen Shot 2021-11-17 at 1 30 46 pm" src="https://user-images.githubusercontent.com/39009487/142108875-db1c30d0-9477-418d-8695-ec051a7549c9.png">

4-15% makes sense overnight but most AU states are doing 40%+ during the day

We also have West Australia data to take care of - what do you need there?

I'll reopen this issue so we can track all EM related tasks

**Comment by nc9** [comment]
<img width="793" alt="Screen Shot 2021-11-17 at 1 45 36 pm" src="https://user-images.githubusercontent.com/39009487/142116264-805c29fe-e97a-4c0b-b620-3fba6c718d21.png">

Just went better - this might be our generation end, i'll double check now

**Comment by madsnedergaard** [comment]
I have another, but similar question/problem with `solar_rooftop` - there seems to be quite a few `null` values in between, which currently means we drop `solar` entirely and the graph looks like this:
![Screenshot 2021-11-17 at 15 09 16](https://user-images.githubusercontent.com/3296643/142216021-d4054922-ddb0-4449-8ee1-825d43418f29.png)

And here's the data:
![Screenshot 2021-11-17 at 15 06 16](https://user-images.githubusercontent.com/3296643/142215850-0d4fe645-b571-4755-b7ef-d6121f6e02ed.png)

Any idea why the `null` values happen? I haven't noticed a pattern to it so far :)

**Comment by pierresegonne** [comment]
> We also have West Australia data to take care of - what do you need there?

Not sure what you mean :). As long as we get solar rooftop for both live and historical, and for all states you support, then we'll be very happy! 

I'll update our parser so that the problem raised by Mads does not result in crashes (which I think should explain the low renewable % you noticed - do you remember by chance what time was it when you took that screenshot?)

**Comment by nc9** [comment]
> Not sure what you mean :)

It's there now! I think it's our output 

> I'll update our parser 

If you're using python on your backend have you had a look at https://github.com/opennem/opennempy ? I've got pydantic schemas for our output, client etc. and I keep it in sync (generally!)

> There seems to be quite a few null values in between 

Looking at this now @madsnedergaard - thanks

**Comment by pierresegonne** [comment]
> It's there now! I think it's our output that might have flashed off for a moment or not caught up

Maybe I'm doing something wrong but when querying e.g https://api.opennem.org.au/stats/power/network/fueltech/NEM/SA1?month=2020-01-01
I don't see any solar_rooftop data. Has this been activated for historical data only in specific states ?

Cheers

**Comment by nc9** [comment]
@pierresegonne let me give you guys an API key to open everything up - might be the best way to handle this so you have full take. Will take a moment, will ping you once its ready on email.

**Comment by pierresegonne** [comment]
Alright sweet, you can ping me at pierre.segonne@tmrow.com :)

**Comment by nc9** [comment]
Great - will likely to get to it over the weekend

**Comment by pierresegonne** [comment]
Hey Nik, any update on your side? :)

**Comment by nc9** [comment]
@pierresegonne almost there - doing a standard API Gateway on AWS with tomorrows prod release

**Comment by nc9** [comment]
@pierresegonne I've added all that archive data on the open endpoints for now - i'll give you adequate notice when its behind API auth, just need to work out more detail on what our strategy is going to be there. I'm going to keep an eye on it in the interim (a few people have figured out already that we provide a backdoor to weather data, which is usually a commercial service)

**Comment by pierresegonne** [comment]
Alright, sweet! 
On our side, we'll implement a quick fix on Thursday to discard hours where there is no solar rooftop data. We estimate that it's better to not show anything on the map (for now, I don't know if you've seen the announcement but we will be displaying estimated fallback on the map soon!) than something completely incorrect. This should only affect a few hours each day as far as I've seen, but at least Australia should be more truthful.

**Comment by chalg** [comment]
Interesting - will the estimated fallback values mentioned above go into your APIs, for example to fill the gap if there is a data outage?

**Comment by nc9** [comment]
> We estimate that it's better to not show anything on the map

Agree completely - we hide days on OpenNEM where we don't have the full set of all data (fixing a bug just on that right now!)

Sometimes it takes a moment for the data to settle - I have to back-fill regularly to get values so feel free to hit that endpoint and do the same
