### ISSUE TITLE
Fueltech Mix By Network API endpoint not working or unclear in documentation

### ISSUE THREAD

**Issue by paulculmsee** [opennem/opennem#50]
Hiya

as per [docco](https://api.opennem.org.au/docs#operation/Fueltech_mix_by_network_stats_fueltech_mix__network_id__get), I am having trouble with this API.  

eg:

https://api.opennem.org.au/stats/fueltech_mix/NEM

results in:

{"detail":[{"loc":["query","network_code"],"msg":"field required","type":"value_error.missing"}]}

The other endpoints seem to be working ok

Paul

**Comment by paulculmsee** [comment]
@nc9 when will we see this light up on the live API?

**Comment by nc9** [comment]
@paulculmsee noticed another issue with that endpoint that I need to patch - will be doing that in a moment and pushing it soon. Likely over the weekend.

**Comment by paulculmsee** [comment]
I see the error message is now gone but now that endpoint appears to hang... 

ie https://api.opennem.org.au/stats/fueltech_mix/NEM times out but other endpoints are ok

**Comment by nc9** [comment]
Thanks - tracking at 

https://github.com/opennem/opennem/issues/57
