### ISSUE TITLE
OpenNem Western Australia (SWIS)

### ISSUE THREAD

**Issue by Geld40** [opennem/opennem#51]
The energy (gwh) data for November has not populated on the OpenNem SWIS page. This information is very useful used in conjunction with the MW measurements. Is there an issue or will this data be no longer populated? Many thanks

**Comment by nc9** [comment]
Thanks for reporting this - we're aware of the issues with WEM at the moment and some of our other data points. We should be clearing them up during the course of the day. I'll keep this thread updated.

**Comment by Geld40** [comment]
Good morning,

Thank you for getting back to me.

The OpenNem page is a superb resource; thank you for setting it up and maintaining it.

Kind regards

Gregg

**Comment by nc9** [comment]
Hi @Geld40  - we've made a ton of improvements to our data ingest and handling errors from our different sources:

<img width="686" alt="Screen Shot 2021-11-29 at 2 19 22 pm" src="https://user-images.githubusercontent.com/39009487/143803555-47bc9ace-07ff-4321-8300-d3463230ee7e.png">

It generates the previous days energy at around 6-7am WA time. There are still a couple of gaps in historic data (primarily with weather data) but they're backfilling at the moment. Let me know if you see or find anything else and thanks

**Comment by Geld40** [comment]
Good morning Nik,

Many thanks

Kind regards

Gregg
