### ISSUE TITLE
Data is missing for the last couple of days

### ISSUE THREAD

**Issue by skovhus** [opennem/opennem#63]
Hi from electricityMap 👋 

It seems like the last datapoint returned from the API is `2022-01-11T01:30:00+00:00 UTC`. This problem is also on https://opennem.org.au/energy/nem/?range=3d&interval=30m

Related issues:
- https://github.com/electricitymap/electricitymap-contrib/issues/3673
- https://github.com/electricitymap/electricitymap-contrib/issues/3672
- https://github.com/electricitymap/electricitymap-contrib/issues/3670
- https://github.com/electricitymap/electricitymap-contrib/issues/3669

Feedback opennem.org.au: I just noticed that the website shows data even if you select 1D or 3D. I would assume that the right hand side of the graph should be now instead of the latest available datapoint.

**Comment by nc9** [comment]
hey @skovhus we had an issue while I was away with one of the source changing and not updating correctly. I've put in some alerts to notify us if this happens again but should be fixed now. Let me know if anything pops up again.
