### ISSUE TITLE
Downloading Historical Data

### ISSUE THREAD

**Issue by BiruthiviB** [opennem/opennem#68]
Is there a way to download historical data from particular power stations dating back to 1999 - present with 30 minute intervals?

**Comment by nc9** [comment]
Hi @BiruthiviB - we restrict this data to partners at the moment (I assume you mean for every interval). Can you email me on nik@opennem.org.au and we can discuss your use case and find a way if we can get you the data

I'll move this issue here as its more relevant on this project

**Comment by eddie-atkinson** [comment]
Hi @nc9, 

I understand why you probably don't want people bulk downloading historical data from your public API. But I this feature should be supported for people who are self-hosting. 

As far as I can tell from reading the code it seems like it's more [efficient](https://github.com/opennem/opennem/blob/082ffd1dacc15feb524dedd569701769de64e119/opennem/api/stats/controllers.py#L434) to only query 7 days in the past? I feel like that function should potentially allow a `date_min` and `date_max` to be specified that default to `None` and override those values with the date 7 days ago and today respectively if they are unspecified. 

I would love to self-host this project but need the ability to query historical data.
