### ISSUE TITLE
Question regarding calculation of emissions intensity

### ISSUE THREAD

**Issue by anguss00** [opennem/opennem#7]
Not a bug - could you please point me to how Carbon Dioxide Emissions Intensity is calculated in OpenNem for each state? Thanks!

**Comment by simonhac** [comment]
we haven't released it yet — if you're seeing anything you're looking at dev data.

but when it is released it will be using AEMO's emissions intensity values for each generator (with educated guesses where missing) and emissions flow tracing for imports/exports.

**Comment by anguss00** [comment]
@simonhac thanks for the help, makes sense :+1:
