### ISSUE TITLE
New facilities not being shown on opennem.org.au

### ISSUE THREAD

**Issue by liwenyip** [opennem/opennem#79]
There are some fairly big facilities which achieved registration many months ago and are being shown on nemlog.com.au but not on opennem.org.au, e.g.

http://nemlog.com.au/show/unit/?k1=WALGRVG1,WALGRVL1
http://nemlog.com.au/show/unit/?k1=METZSF1

**Comment by nc9** [comment]
Hi @liwenyip we account for them in our aggregate stats but they don't have facility pages as yet. I will leave this issue open to track when it is up to date. Thanks.
