### ISSUE TITLE
Victorian station with no infomation

### ISSUE THREAD

**Issue by coreydrum** [opennem/opennem#89]
Not sure if this is the correct method to report issues, but I have been experimenting and in my list of victoria stations I am getting a station with the following information.

Station ID:466
Station name: ENOC MSAP

It is not listed on opennem.org.au and it has no fuel type information or energy output

**Comment by nc9** [comment]
Thanks for reporting this - i'll take a look at it

**Comment by nc9** [comment]
`VENUS1` is the DUID and it's a registered load - so it doesn't have a fueltech
