### ISSUE TITLE
Charging/Discharging DUIDs for BESSes are the wrong way around

### ISSUE THREAD

**Issue by liwenyip** [opennem/opennem#93]
Hi,

I think the DUIDs for every BESS are the wrong way around:

The xxxxxG1 DUIDs are for discharging / generating
The xxxxxL1 DUIDs are for charging / loads

![image](https://user-images.githubusercontent.com/16456010/176333582-55a82fb7-da35-4834-9bfa-5cb9b06596c8.png)

![image](https://user-images.githubusercontent.com/16456010/176333009-da92d2d4-c2f0-405e-b444-6e0206ec9ee7.png)

![image](https://user-images.githubusercontent.com/16456010/176333529-b082a4dd-4178-4145-a52a-5bdce8e379e8.png)

And in the historical energy data, the Battery (Discharging) MWh is more than the Battery (Charging) MWh, which isn't right - charge energy should always be 10-20% more than discharge energy due to round-trip energy losses.

![image](https://user-images.githubusercontent.com/16456010/176333193-22bff82c-f0ff-4e87-8686-c81a9712ce38.png)

**Comment by nc9** [comment]
Thanks for reporting this - absolutely a bug. Will be jumping onto it shortly
