### ISSUE TITLE
Facility pages not rendering/accessing their data.

### ISSUE THREAD

**Issue by aleith** [opennem/opennem#95]
I've been reading from openNEM and typing energy data by facility values into a spreadsheet for all of WA for a couple of days on and off. Presently I'm not able to access the data. (See images). It could be a temporary glitch or a recent update. It's happening in both Safari and FireFox.

As a work around and time saver, is there a way I can get an CSV file of the annual output of each facility per Financial Year? You can do it on the main Energy page but not the Facilities page I think.  Could be a good feature. Be good to know the source of the emissions intensity for the coal and gas units too. Does it come from the Australian regulator from when we had a C price or is it provided by the owners or sourced from online articles?

 
<img width="1061" alt="Screen Shot 2022-06-29 at 11 59 10 am" src="https://user-images.githubusercontent.com/1528794/176335169-ff8b0a51-dce2-4e62-b656-0e8fb088e7cc.png">
<img width="641" alt="Screen Shot 2022-06-29 at 11 59 00 am" src="https://user-images.githubusercontent.com/1528794/176335174-a06def2a-7bbc-4a92-a706-b371d7c40722.png">
<img width="1069" alt="Screen Shot 2022-06-29 at 11 58 57 am" src="https://user-images.githubusercontent.com/1528794/176335180-822d7c3c-64d9-4930-9f57-20f09c4c0734.png">

**Comment by nc9** [comment]
transferred into the main opennem repo - we're attempting to consolidate issues here.

**Comment by nc9** [comment]
> As a work around and time saver, is there a way I can get an CSV file of the annual output of each facility per Financial Year?

You can use our python client - I'll whip up an example for you (I've been meaning to include examples in our documentation) 

Would you be comfortable using the python client?

**Comment by aleith** [comment]
yes I think so. I'm not a python programmer but ok using existing python applications in virtual environments.

**Comment by aleith** [comment]
facilities data feed was down again today, back up now.

**Comment by nc9** [comment]
Fixed in 3.10.10 with better monitoring
